spring.application.name=CaseStudy

server.port=8080

spring.datasource.url=jdbc:postgresql://host.docker.internal:5432/postgres
#spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

jwt.secret=${JWT_SECRET}
jwt.expiration=300000

app.cors.allowed-mf-container=http://localhost:3003
app.cors.allowed-nginx=http://localhost:90

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

spring.datasource.hikari.maximum-pool-size=10

spring.data.redis.host=${SPRING_DATA_REDIS_HOST:localhost}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6379}

spring.data.redis.timeout=2000ms
refresh.token.ttl=604800000


# Circuit Breaker Configuration
resilience4j.circuitbreaker.instances.userDatabase.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.userDatabase.wait-duration-in-open-state=30000
resilience4j.circuitbreaker.instances.userDatabase.sliding-window-size=10
resilience4j.circuitbreaker.instances.userDatabase.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.userDatabase.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.userDatabase.automatic-transition-from-open-to-half-open-enabled=true

# timeout configuration
resilience4j.timelimiter.instances.userDatabase.timeout-duration=3s
resilience4j.circuitbreaker.instances.userDatabase.record-exceptions=org.springframework.dao.DataAccessException,java.util.concurrent.TimeoutException

# Resilience4j Rate Limiter Configuration
resilience4j.ratelimiter.instances.globalRateLimiter.limitForPeriod=5
resilience4j.ratelimiter.instances.globalRateLimiter.limitRefreshPeriod=30s
resilience4j.ratelimiter.instances.globalRateLimiter.timeoutDuration=0s
