spring.application.name=CaseStudy

server.port=8080

spring.datasource.url=jdbc:postgresql://host.docker.internal:5432/postgres
#spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

jwt.secret=${JWT_SECRET}
jwt.expiration=1800000

app.cors.allowed-mf1=http://localhost:3001
app.cors.allowed-mf2=http://localhost:3002
app.cors.allowed-mf-container=http://localhost:3003
app.cors.allowed-nginx=http://localhost:90

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

spring.datasource.hikari.maximum-pool-size=10

spring.data.redis.host=${SPRING_DATA_REDIS_HOST:localhost}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6379}

spring.data.redis.timeout=2000ms
